# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arthur Phillip Silva
email: artphil@ufmg.br
description: > # this means to ignore newlines until "baseurl:"
  Arthur Phillip Silva is a Information Systems Student @ UFMG
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://artphil.github.io." # the base hostname & protocol for your site
twitter_username: artphil7
github_username:  artphil

# Build settings
markdown: kramdown
# theme: jekyll-theme-tactile
